/**
 * Generate a Go HTTP API: chi router, sqlx-style pgx connection, one handler/repo
 * per model, Dockerfile, go.mod, .env. Idiomatic Go — no proprietary runtime,
 * no SDK to import, runs anywhere with `go build && ./app`.
 */

import type { ProjectConfig, GeneratedFile, ModelDef, FieldDef } from "./index";
import { modelToCreateTable, tableName } from "./sql";

const GO_TYPE_MAP: Record<FieldDef["type"], string> = {
  string: "string",
  text: "string",
  int: "int64",
  float: "float64",
  bool: "bool",
  timestamp: "time.Time",
  uuid: "string",
  json: "json.RawMessage",
};

export function generateGo(cfg: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const models = cfg.models ?? [];
  const modName = goModule(cfg.projectName);

  // go.mod
  files.push({
    path: "api/go.mod",
    content: `module ${modName}

go 1.22

require (
\tgithub.com/go-chi/chi/v5 v5.0.12
\tgithub.com/go-chi/cors v1.2.1
\tgithub.com/jackc/pgx/v5 v5.5.5
\tgithub.com/google/uuid v1.6.0
)
`,
  });

  // .env.example
  files.push({
    path: "api/.env.example",
    content: `DATABASE_URL=postgres://postgres:postgres@localhost:5432/${slug(cfg.projectName)}
PORT=8080
ALLOWED_ORIGIN=http://localhost:3000
`,
  });

  // Dockerfile (multi-stage, scratch final)
  files.push({
    path: "api/Dockerfile",
    content: `# Build
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app ./cmd/server

# Runtime
FROM gcr.io/distroless/static:nonroot
COPY --from=build /app /app
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/app"]
`,
  });

  // Migration
  const migration = [
    "-- Auto-generated by Seowebsitesbuilder.",
    "-- Apply with `psql $DATABASE_URL -f db/0001_init.sql`.",
    "",
    "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
    "",
    ...models.map(modelToCreateTable),
  ].join("\n");
  files.push({ path: "api/db/0001_init.sql", content: migration });

  // main.go
  files.push({ path: "api/cmd/server/main.go", content: mainGo(modName, models) });

  // db package
  files.push({ path: "api/internal/db/db.go", content: dbGo() });

  // One model file per model — types + handlers
  for (const m of models) {
    files.push({ path: `api/internal/models/${tableName(m.name)}.go`, content: modelGo(m) });
  }

  // README
  files.push({
    path: "api/README.md",
    content: `# Go API

Generated by Seowebsitesbuilder. Idiomatic Go using chi + pgx. No proprietary runtime.

## Run locally

\`\`\`bash
cp .env.example .env
# Start a Postgres anywhere — for example:
# docker run -d --name pg -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:16-alpine
psql $DATABASE_URL -f db/0001_init.sql
go run ./cmd/server
\`\`\`

## Build for production

\`\`\`bash
docker build -t myapi .
docker run --rm -p 8080:8080 -e DATABASE_URL=$DATABASE_URL myapi
\`\`\`

## Endpoints

${models.map((m) => {
    const tn = tableName(m.name);
    return `- \`GET /${tn}\` — list ${tn}\n- \`POST /${tn}\` — create one\n- \`GET /${tn}/{id}\` — fetch one\n- \`DELETE /${tn}/{id}\` — remove one`;
  }).join("\n")}

Edit freely. There's no SDK or framework to update — just standard library + chi.
`,
  });

  return files;
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "app";
}

function goModule(name: string): string {
  return slug(name);
}

function mainGo(modName: string, models: ModelDef[]): string {
  const routeRegistrations = models.length === 0
    ? "\t// No models defined — add routes here."
    : models.map((m) => {
        const tn = tableName(m.name);
        return `\tr.Route("/${tn}", func(r chi.Router) {
\t\tr.Get("/", models.List${m.name}(pool))
\t\tr.Post("/", models.Create${m.name}(pool))
\t\tr.Get("/{id}", models.Get${m.name}(pool))
\t\tr.Delete("/{id}", models.Delete${m.name}(pool))
\t})`;
      }).join("\n");

  return `package main

import (
\t"context"
\t"log"
\t"net/http"
\t"os"
\t"time"

\t"${modName}/internal/db"
${models.length ? `\t"${modName}/internal/models"\n` : ""}
\t"github.com/go-chi/chi/v5"
\t"github.com/go-chi/chi/v5/middleware"
\t"github.com/go-chi/cors"
)

func main() {
\tctx := context.Background()
\tpool, err := db.Connect(ctx, os.Getenv("DATABASE_URL"))
\tif err != nil {
\t\tlog.Fatalf("db: %v", err)
\t}
\tdefer pool.Close()

\tr := chi.NewRouter()
\tr.Use(middleware.RequestID)
\tr.Use(middleware.RealIP)
\tr.Use(middleware.Logger)
\tr.Use(middleware.Recoverer)
\tr.Use(middleware.Timeout(60 * time.Second))
\tr.Use(cors.Handler(cors.Options{
\t\tAllowedOrigins: []string{firstNonEmpty(os.Getenv("ALLOWED_ORIGIN"), "*")},
\t\tAllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
\t\tAllowedHeaders: []string{"*"},
\t}))

\tr.Get("/healthz", func(w http.ResponseWriter, _ *http.Request) {
\t\tw.WriteHeader(http.StatusOK)
\t\tw.Write([]byte("ok"))
\t})

${routeRegistrations}

\taddr := ":" + firstNonEmpty(os.Getenv("PORT"), "8080")
\tlog.Printf("listening on %s", addr)
\tif err := http.ListenAndServe(addr, r); err != nil {
\t\tlog.Fatal(err)
\t}
}

func firstNonEmpty(a, b string) string {
\tif a != "" {
\t\treturn a
\t}
\treturn b
}
`;
}

function dbGo(): string {
  return `package db

import (
\t"context"

\t"github.com/jackc/pgx/v5/pgxpool"
)

func Connect(ctx context.Context, url string) (*pgxpool.Pool, error) {
\tcfg, err := pgxpool.ParseConfig(url)
\tif err != nil {
\t\treturn nil, err
\t}
\tcfg.MaxConns = 10
\treturn pgxpool.NewWithConfig(ctx, cfg)
}
`;
}

function modelGo(m: ModelDef): string {
  const tn = tableName(m.name);
  const goFields = m.fields.map((f) => {
    const goType = GO_TYPE_MAP[f.type];
    const optional = f.required ? "" : ",omitempty";
    return `\t${capitalize(f.name)} ${goType} \`json:"${f.name}${optional}" db:"${f.name}"\``;
  }).join("\n");

  const insertCols = m.fields.map((f) => f.name).join(", ");
  const insertPlaceholders = m.fields.map((_, i) => `$${i + 1}`).join(", ");
  const insertReturnFields = ["id", "created_at", "updated_at", ...m.fields.map((f) => f.name)].join(", ");
  const insertScanArgs = ["&row.ID", "&row.CreatedAt", "&row.UpdatedAt", ...m.fields.map((f) => `&row.${capitalize(f.name)}`)].join(", ");
  const insertInputArgs = m.fields.map((f) => `body.${capitalize(f.name)}`).join(", ");

  const usesTime = m.fields.some((f) => f.type === "timestamp") || true; // created_at / updated_at always
  const usesJSON = m.fields.some((f) => f.type === "json");

  const imports = [
    `"context"`,
    `"encoding/json"`,
    `"net/http"`,
    `"time"`,
  ];
  if (usesJSON) {
    // already imported encoding/json above
  }

  return `package models

import (
\t${imports.join("\n\t")}

\t"github.com/go-chi/chi/v5"
\t"github.com/jackc/pgx/v5/pgxpool"
)

type ${m.name} struct {
\tID        string    \`json:"id" db:"id"\`
\tCreatedAt time.Time \`json:"created_at" db:"created_at"\`
\tUpdatedAt time.Time \`json:"updated_at" db:"updated_at"\`
${goFields}
}

func List${m.name}(pool *pgxpool.Pool) http.HandlerFunc {
\treturn func(w http.ResponseWriter, r *http.Request) {
\t\trows, err := pool.Query(r.Context(), \`SELECT id, created_at, updated_at, ${m.fields.map((f) => f.name).join(", ")} FROM ${tn} ORDER BY created_at DESC\`)
\t\tif err != nil {
\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)
\t\t\treturn
\t\t}
\t\tdefer rows.Close()
\t\tout := []${m.name}{}
\t\tfor rows.Next() {
\t\t\tvar row ${m.name}
\t\t\tif err := rows.Scan(${insertScanArgs}); err != nil {
\t\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)
\t\t\t\treturn
\t\t\t}
\t\t\tout = append(out, row)
\t\t}
\t\twriteJSON(w, http.StatusOK, out)
\t}
}

func Get${m.name}(pool *pgxpool.Pool) http.HandlerFunc {
\treturn func(w http.ResponseWriter, r *http.Request) {
\t\tid := chi.URLParam(r, "id")
\t\tvar row ${m.name}
\t\terr := pool.QueryRow(r.Context(),
\t\t\t\`SELECT id, created_at, updated_at, ${m.fields.map((f) => f.name).join(", ")} FROM ${tn} WHERE id = $1\`, id,
\t\t).Scan(${insertScanArgs})
\t\tif err != nil {
\t\t\thttp.Error(w, "not found", http.StatusNotFound)
\t\t\treturn
\t\t}
\t\twriteJSON(w, http.StatusOK, row)
\t}
}

func Create${m.name}(pool *pgxpool.Pool) http.HandlerFunc {
\treturn func(w http.ResponseWriter, r *http.Request) {
\t\tvar body ${m.name}
\t\tif err := json.NewDecoder(r.Body).Decode(&body); err != nil {
\t\t\thttp.Error(w, "bad json", http.StatusBadRequest)
\t\t\treturn
\t\t}
\t\tvar row ${m.name}
\t\terr := pool.QueryRow(r.Context(),
\t\t\t\`INSERT INTO ${tn} (${insertCols}) VALUES (${insertPlaceholders}) RETURNING ${insertReturnFields}\`,
\t\t\t${insertInputArgs},
\t\t).Scan(${insertScanArgs})
\t\tif err != nil {
\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)
\t\t\treturn
\t\t}
\t\twriteJSON(w, http.StatusCreated, row)
\t}
}

func Delete${m.name}(pool *pgxpool.Pool) http.HandlerFunc {
\treturn func(w http.ResponseWriter, r *http.Request) {
\t\tid := chi.URLParam(r, "id")
\t\t_, err := pool.Exec(r.Context(), \`DELETE FROM ${tn} WHERE id = $1\`, id)
\t\tif err != nil {
\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)
\t\t\treturn
\t\t}
\t\tw.WriteHeader(http.StatusNoContent)
\t}
}

func writeJSON(w http.ResponseWriter, status int, v any) {
\tw.Header().Set("Content-Type", "application/json")
\tw.WriteHeader(status)
\t_ = json.NewEncoder(w).Encode(v)
}

var _ = context.Background
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}
