/**
 * Generate a direct-Postgres backend: connection pool, typed repository per model,
 * SQL migrations, and a docker-compose dev DB. The user owns everything and can
 * point it at any Postgres host (Neon, Supabase, RDS, self-hosted).
 */

import type { ProjectConfig, GeneratedFile } from "./index";
import { modelToCreateTable, modelToTSType, tableName } from "./sql";

export function generatePostgres(cfg: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const models = cfg.models ?? [];
  const isPhp = cfg.framework === "php";

  // .env.example
  files.push({
    path: ".env.example",
    content: `# Postgres connection — point this at any Postgres host you control
DATABASE_URL=postgres://postgres:postgres@localhost:5432/${slug(cfg.projectName)}
`,
  });

  // docker-compose for a dev DB the user can spin up locally
  files.push({
    path: "docker-compose.yml",
    content: `services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${slug(cfg.projectName)}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
`,
  });

  // Migration
  const migration = [
    "-- Auto-generated by Seowebsitesbuilder. Apply with `psql $DATABASE_URL -f db/0001_init.sql`.",
    "-- Safe to re-run.",
    "",
    "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
    "",
    ...models.map(modelToCreateTable),
  ].join("\n");
  files.push({ path: "db/0001_init.sql", content: migration });

  // Client + repositories
  if (isPhp) {
    files.push({ path: "lib/db.php", content: phpClient() });
    for (const m of models) {
      files.push({ path: `lib/repos/${tableName(m.name)}.php`, content: phpRepo(m) });
    }
  } else {
    files.push({ path: "lib/db.ts", content: tsClient(cfg.framework) });
    if (models.length) {
      files.push({
        path: "lib/types.ts",
        content: models.map(modelToTSType).join("\n\n") + "\n",
      });
    }
    for (const m of models) {
      files.push({ path: `lib/repos/${tableName(m.name)}.ts`, content: tsRepo(m) });
    }
  }

  // README addendum
  files.push({
    path: "POSTGRES.md",
    content: `# Postgres setup

This project was generated with a direct Postgres connection. You own the schema and the data — there is no Seowebsitesbuilder runtime dependency.

## Local dev (with Docker)

\`\`\`bash
docker compose up -d
psql "postgres://postgres:postgres@localhost:5432/${slug(cfg.projectName)}" -f db/0001_init.sql
\`\`\`

## Production

Point \`DATABASE_URL\` at any managed Postgres (Neon, Supabase, RDS, Fly Postgres, self-hosted). Apply the migration the same way.

## Code layout

- \`lib/db.${isPhp ? "php" : "ts"}\` — connection pool, no framework dependency
- \`lib/repos/*\` — one typed repository per model. Edit freely.
- \`db/*.sql\` — migrations. Add new ones as numbered files; apply in order.

The generated client uses the standard \`pg\` driver${isPhp ? " via PDO" : ""}. Swap it for an ORM if you want — nothing in this codebase ties you to it.
`,
  });

  return files;
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "app";
}

function tsClient(framework: ProjectConfig["framework"]): string {
  const isNext = framework === "nextjs";
  const envExpr = isNext ? "process.env.DATABASE_URL!" : `import.meta.env.DATABASE_URL!`;
  return `// Auto-generated. Edit freely. Single shared pool — safe under serverless and long-lived servers.
import { Pool } from "pg";

declare global {
  // eslint-disable-next-line no-var
  var __pgPool: Pool | undefined;
}

export const db: Pool =
  globalThis.__pgPool ??
  (globalThis.__pgPool = new Pool({
    connectionString: ${envExpr},
    max: 10,
    idleTimeoutMillis: 30_000,
  }));

export async function query<T = any>(sql: string, params: any[] = []): Promise<T[]> {
  const { rows } = await db.query<T>(sql, params);
  return rows;
}

export async function one<T = any>(sql: string, params: any[] = []): Promise<T | null> {
  const rows = await query<T>(sql, params);
  return rows[0] ?? null;
}
`;
}

function tsRepo(m: import("./index").ModelDef): string {
  const tn = tableName(m.name);
  const insertCols = m.fields.map((f) => f.name);
  const insertPlaceholders = insertCols.map((_, i) => `$${i + 1}`).join(", ");
  const updateAssigns = insertCols.map((c, i) => `${c} = $${i + 2}`).join(", ");
  return `// Auto-generated. Edit freely.
import { query, one } from "../db";
import type { ${m.name} } from "../types";

export const ${tn} = {
  list(): Promise<${m.name}[]> {
    return query<${m.name}>(\`SELECT * FROM ${tn} ORDER BY created_at DESC\`);
  },
  get(id: string): Promise<${m.name} | null> {
    return one<${m.name}>(\`SELECT * FROM ${tn} WHERE id = $1\`, [id]);
  },
  async create(input: Omit<${m.name}, "id" | "created_at" | "updated_at">): Promise<${m.name}> {
    const row = await one<${m.name}>(
      \`INSERT INTO ${tn} (${insertCols.join(", ")}) VALUES (${insertPlaceholders}) RETURNING *\`,
      [${insertCols.map((c) => `(input as any).${c}`).join(", ")}],
    );
    return row!;
  },
  async update(id: string, input: Partial<Omit<${m.name}, "id" | "created_at" | "updated_at">>): Promise<${m.name} | null> {
    const fields = Object.keys(input);
    if (fields.length === 0) return this.get(id);
    const sets = fields.map((f, i) => \`\${f} = $\${i + 2}\`).join(", ");
    const values = fields.map((f) => (input as any)[f]);
    return one<${m.name}>(
      \`UPDATE ${tn} SET \${sets} WHERE id = $1 RETURNING *\`,
      [id, ...values],
    );
  },
  async remove(id: string): Promise<void> {
    await query(\`DELETE FROM ${tn} WHERE id = $1\`, [id]);
  },
};
`;
}

function phpClient(): string {
  return `<?php
// Auto-generated. Edit freely. PDO connection, lazy-initialised once per request.
function db(): PDO {
  static $pdo = null;
  if ($pdo) return $pdo;
  $url = getenv("DATABASE_URL") ?: "";
  if (!$url) throw new RuntimeException("DATABASE_URL is not set");
  $parts = parse_url($url);
  $dsn = "pgsql:host={$parts['host']};port=" . ($parts['port'] ?? 5432) . ";dbname=" . ltrim($parts['path'] ?? '', '/');
  $pdo = new PDO($dsn, $parts['user'] ?? '', $parts['pass'] ?? '', [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
  ]);
  return $pdo;
}
`;
}

function phpRepo(m: import("./index").ModelDef): string {
  const tn = tableName(m.name);
  const cols = m.fields.map((f) => f.name);
  return `<?php
// Auto-generated. Edit freely.
require_once __DIR__ . "/../db.php";

class ${m.name}Repo {
  public static function list(): array {
    return db()->query("SELECT * FROM ${tn} ORDER BY created_at DESC")->fetchAll();
  }
  public static function get(string $id): ?array {
    $st = db()->prepare("SELECT * FROM ${tn} WHERE id = :id");
    $st->execute([":id" => $id]);
    $row = $st->fetch();
    return $row ?: null;
  }
  public static function create(array $input): array {
    $cols = ${JSON.stringify(cols)};
    $placeholders = array_map(fn($c) => ":$c", $cols);
    $sql = "INSERT INTO ${tn} (" . implode(", ", $cols) . ") VALUES (" . implode(", ", $placeholders) . ") RETURNING *";
    $st = db()->prepare($sql);
    foreach ($cols as $c) $st->bindValue(":$c", $input[$c] ?? null);
    $st->execute();
    return $st->fetch();
  }
  public static function remove(string $id): void {
    $st = db()->prepare("DELETE FROM ${tn} WHERE id = :id");
    $st->execute([":id" => $id]);
  }
}
`;
}
