/**
 * Generate Supabase scaffolding: client, migrations, RLS-friendly query helpers, .env.
 * Output runs against the user's own Supabase project — we never proxy.
 */

import type { ProjectConfig, GeneratedFile } from "./index";
import { modelToCreateTable, modelToTSType, tableName } from "./sql";

export function generateSupabase(cfg: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const models = cfg.models ?? [];

  // .env.example
  files.push({
    path: ".env.example",
    content: `# Supabase connection — fill these from your project's API settings
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
# Service role key (server-side only, never expose to the browser)
SUPABASE_SERVICE_ROLE_KEY=
`,
  });

  // Client setup — varies slightly by framework
  files.push({
    path: cfg.framework === "php" ? "lib/supabase.php" : "lib/supabase.ts",
    content: cfg.framework === "php" ? phpClient() : tsClient(cfg.framework),
  });

  // Migration: combined CREATE TABLE + RLS
  const migration = [
    "-- Auto-generated by Seowebsitesbuilder. Run via the Supabase SQL editor or CLI.",
    "-- Safe to re-run.",
    "",
    "create extension if not exists pgcrypto;",
    "",
    ...models.map(modelToCreateTable),
    "",
    "-- RLS — locked down by default. Edit per-table policies for your access pattern.",
    ...models.map((m) => `alter table ${tableName(m.name)} enable row level security;`),
    "",
    ...models.map((m) => `-- example: allow authenticated users to read their own ${tableName(m.name)}\n-- create policy "owner_read" on ${tableName(m.name)} for select using (auth.uid() = owner_id);`),
  ].join("\n");
  files.push({ path: "supabase/migrations/0001_init.sql", content: migration });

  // Types
  if (cfg.framework !== "php" && models.length) {
    files.push({
      path: "lib/types.ts",
      content: models.map(modelToTSType).join("\n\n") + "\n",
    });
  }

  // README addendum
  files.push({
    path: "SUPABASE.md",
    content: `# Supabase setup

This project was generated with Supabase as the backend. You own the schema and the data.

1. Create a Supabase project at https://supabase.com (free tier is fine to start).
2. Copy your project URL and anon key into \`.env\`.
3. Run the migration:
   \`\`\`bash
   supabase db push
   # or paste supabase/migrations/0001_init.sql into the SQL editor
   \`\`\`
4. Tighten RLS policies for your access pattern. The defaults are deny-all.

The generated \`lib/supabase.${cfg.framework === "php" ? "php" : "ts"}\` is a thin client. Edit it freely — there's no Seowebsitesbuilder runtime dependency.
`,
  });

  return files;
}

function tsClient(framework: ProjectConfig["framework"]): string {
  const isNext = framework === "nextjs";
  return `// Auto-generated. Edit freely.
import { createClient } from "@supabase/supabase-js";
${isNext ? `\nconst url = process.env.NEXT_PUBLIC_SUPABASE_URL!;\nconst anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;\n` : `\nconst url = import.meta.env.PUBLIC_SUPABASE_URL!;\nconst anon = import.meta.env.PUBLIC_SUPABASE_ANON_KEY!;\n`}
export const supabase = createClient(url, anon, {
  auth: { persistSession: typeof window !== "undefined" },
});

// Server-only client (use service role key — never import this from a client component).
export function supabaseServer() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) throw new Error("SUPABASE_SERVICE_ROLE_KEY missing");
  return createClient(url, key, { auth: { persistSession: false } });
}
`;
}

function phpClient(): string {
  return `<?php
// Minimal Supabase REST wrapper for PHP. Edit freely.
class Supabase {
  private string $url; private string $key;
  function __construct() {
    $this->url = getenv("SUPABASE_URL") ?: "";
    $this->key = getenv("SUPABASE_ANON_KEY") ?: "";
  }
  function from(string $table) {
    return new SupabaseQuery($this->url, $this->key, $table);
  }
}
class SupabaseQuery {
  function __construct(private string $url, private string $key, private string $table) {}
  function select(string $cols = "*"): array {
    $ch = curl_init("$this->url/rest/v1/$this->table?select=$cols");
    curl_setopt_array($ch, [
      CURLOPT_HTTPHEADER => ["apikey: $this->key", "Authorization: Bearer $this->key"],
      CURLOPT_RETURNTRANSFER => true,
    ]);
    $body = curl_exec($ch);
    return json_decode($body, true) ?: [];
  }
}
`;
}
