/**
 * Custom domains for published projects.
 *
 * Flow:
 *   1. User adds a domain on their published project ("mybusiness.com").
 *   2. We check that the domain's DNS resolves to our VPS (A or CNAME chain).
 *   3. We write the domain → slug mapping into /etc/caddy/dynamic.caddy and
 *      reload Caddy. Caddy uses on-demand TLS (validated by our /api/domains/ask
 *      endpoint) so a Let's Encrypt cert is issued on the first request.
 *
 * Plan limit: solo=3, pro=10, agency=∞.
 */

import { Router, Response, Request } from "express";
import { z } from "zod";
import { exec } from "node:child_process";
import { promisify } from "node:util";
import dns from "node:dns/promises";
import fs from "fs-extra";
import { AuthedRequest, requireAuth } from "./auth";
import { one, query } from "./db";
import { PLANS, userPlan } from "./plans";

const execAsync = promisify(exec);

export const domainsRouter = Router();        // authed CRUD
export const domainsAskRouter = Router();     // public ask endpoint for Caddy

const DYNAMIC_CADDY_PATH = process.env.DYNAMIC_CADDY_PATH || "/etc/caddy/dynamic.caddy";
const VPS_IP = process.env.VPS_IP || "187.77.74.66";
const SEOSITES_ROOT = process.env.SEOSITES_ROOT || "/var/seosites";

const DOMAIN_RE = /^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i;
const AddBody = z.object({
  publishId: z.string().uuid(),
  domain: z.string().min(4).max(253).regex(DOMAIN_RE, "Must be a valid domain (no protocol, no path)"),
});

interface DomainRow {
  id: string;
  user_id: string;
  publish_id: string;
  domain: string;
  status: string;
  verified_at: string | null;
}

interface PublishRow { id: string; project_id: string; slug: string }

async function resolvesToUs(domain: string): Promise<{ ok: boolean; reason?: string }> {
  try {
    const addrs = await dns.resolve4(domain).catch(() => [] as string[]);
    if (addrs.includes(VPS_IP)) return { ok: true };
    // Try resolving as CNAME chain — terminal A record may still be ours.
    try {
      const cname = await dns.resolveCname(domain);
      if (cname.length > 0) {
        const a2 = await dns.resolve4(cname[0]).catch(() => [] as string[]);
        if (a2.includes(VPS_IP)) return { ok: true };
        return { ok: false, reason: `CNAME → ${cname[0]} resolves to ${a2.join(",") || "nothing"} (need ${VPS_IP})` };
      }
    } catch { /* no CNAME, fall through */ }
    return { ok: false, reason: `A record resolves to ${addrs.join(", ") || "nothing"} (need ${VPS_IP})` };
  } catch (err: any) {
    return { ok: false, reason: err?.code || "DNS lookup failed" };
  }
}

/** Regenerate /etc/caddy/dynamic.caddy from current verified domains and reload Caddy. */
async function rewriteDynamicCaddyfile(): Promise<void> {
  const rows = await query<{ domain: string; slug: string }>(
    `SELECT cd.domain, p.slug
       FROM custom_domains cd
       JOIN publishes p ON p.id = cd.publish_id
      WHERE cd.status IN ('verified','active')`,
  );
  const blocks = rows.map((r) => `
${r.domain}, www.${r.domain} {
  tls { on_demand }
  encode zstd gzip
  root * ${SEOSITES_ROOT}/${r.slug}
  try_files {path} {path}/ {path}.html
  file_server
  header Cache-Control "public, max-age=300, s-maxage=86400"
}`).join("\n");
  const content = `# Auto-generated by the orchestrator. Do not edit by hand.\n# ${rows.length} custom domain${rows.length === 1 ? "" : "s"} mapped, last updated ${new Date().toISOString()}.\n${blocks || "# (no custom domains configured)"}\n`;
  await fs.writeFile(DYNAMIC_CADDY_PATH, content, { mode: 0o644 });
  // Reload — runs as root in pm2.
  try {
    await execAsync("systemctl reload caddy", { timeout: 10_000 });
  } catch (err: any) {
    console.error("[domains] caddy reload failed:", err?.message || err);
    throw new Error("Caddy reload failed; check orchestrator logs.");
  }
}

domainsRouter.use(requireAuth);

domainsRouter.get("/", async (req: AuthedRequest, res: Response) => {
  const rows = await query<DomainRow & { slug: string }>(
    `SELECT cd.id, cd.domain, cd.status, cd.verified_at, p.slug, cd.publish_id, cd.user_id
       FROM custom_domains cd JOIN publishes p ON p.id = cd.publish_id
      WHERE cd.user_id = $1
      ORDER BY cd.created_at DESC`,
    [req.user!.id],
  );
  return res.json({
    domains: rows.map((r) => ({
      id: r.id, domain: r.domain, status: r.status,
      verifiedAt: r.verified_at, slug: r.slug, publishId: r.publish_id,
    })),
  });
});

domainsRouter.post("/", async (req: AuthedRequest, res: Response) => {
  const parsed = AddBody.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });
  const domain = parsed.data.domain.toLowerCase().replace(/^www\./, "");

  // Ownership: publish must belong to this user
  const pub = await one<PublishRow & { user_id: string }>(
    `SELECT p.id, p.project_id, p.slug, pr.owner_id AS user_id
       FROM publishes p JOIN projects pr ON pr.id = p.project_id
      WHERE p.id = $1 AND pr.owner_id = $2`,
    [parsed.data.publishId, req.user!.id],
  );
  if (!pub) return res.status(404).json({ error: "Publish not found" });

  // Plan gate — admins bypass.
  const plan = await userPlan(req.user!.id);
  const limit = PLANS[plan].maxCustomDomains;
  const countRow = await one<{ count: string }>(
    "SELECT COUNT(*)::text AS count FROM custom_domains WHERE user_id = $1",
    [req.user!.id],
  );
  const count = parseInt(countRow?.count ?? "0", 10);
  if (!req.user!.is_admin && limit !== Infinity && count >= limit) {
    return res.status(402).json({
      error: `Your ${PLANS[plan].name} plan allows ${limit} custom domain${limit === 1 ? "" : "s"}. Upgrade at /billing for more.`,
    });
  }

  // Reserved suffix — don't let users hijack our own brand
  if (domain.endsWith(".seosites.app") || domain.endsWith(".seowebsitesbuilder.com")) {
    return res.status(400).json({ error: "That domain is reserved." });
  }

  // DNS check
  const dnsResult = await resolvesToUs(domain);
  if (!dnsResult.ok) {
    return res.status(400).json({
      error: "Domain doesn't point to our server yet.",
      hint: `Add an A record: ${domain} → ${VPS_IP}. Reason: ${dnsResult.reason}`,
    });
  }

  try {
    const inserted = await one<{ id: string }>(
      `INSERT INTO custom_domains (user_id, publish_id, domain, status, verified_at)
       VALUES ($1, $2, $3, 'verified', now()) RETURNING id`,
      [req.user!.id, pub.id, domain],
    );
    await rewriteDynamicCaddyfile();
    return res.json({
      ok: true,
      id: inserted!.id, domain, status: "verified",
      url: `https://${domain}`,
    });
  } catch (err: any) {
    if (err?.code === "23505") return res.status(409).json({ error: "That domain is already attached to another project." });
    return res.status(500).json({ error: String(err?.message || err) });
  }
});

domainsRouter.post("/:id/recheck", async (req: AuthedRequest, res: Response) => {
  const row = await one<DomainRow>(
    "SELECT id, user_id, publish_id, domain, status, verified_at FROM custom_domains WHERE id = $1 AND user_id = $2",
    [req.params.id, req.user!.id],
  );
  if (!row) return res.status(404).json({ error: "Not found" });
  const dnsResult = await resolvesToUs(row.domain);
  if (!dnsResult.ok) return res.status(400).json({ error: "DNS doesn't point to us", hint: dnsResult.reason });
  await query(
    "UPDATE custom_domains SET status='verified', verified_at = now() WHERE id = $1",
    [row.id],
  );
  await rewriteDynamicCaddyfile();
  return res.json({ ok: true, status: "verified" });
});

domainsRouter.delete("/:id", async (req: AuthedRequest, res: Response) => {
  const row = await one<DomainRow>(
    "SELECT id, domain FROM custom_domains WHERE id = $1 AND user_id = $2",
    [req.params.id, req.user!.id],
  );
  if (!row) return res.status(404).json({ error: "Not found" });
  await query("DELETE FROM custom_domains WHERE id = $1", [row.id]);
  await rewriteDynamicCaddyfile();
  return res.json({ ok: true });
});

/**
 * Public `ask` endpoint Caddy hits before issuing a Let's Encrypt cert for a
 * custom domain. Returns 200 only if we have a verified row for it.
 */
domainsAskRouter.get("/domains/ask", async (req: Request, res: Response) => {
  const domain = String(req.query.domain || "").toLowerCase();
  if (!domain) return res.status(400).send("missing domain");
  // Reject our own apex/wildcard — those have other certs
  if (domain === "seowebsitesbuilder.com" || domain.endsWith(".seowebsitesbuilder.com")) return res.status(404).send("no");
  if (domain === "seosites.app" || domain.endsWith(".seosites.app")) return res.status(404).send("no");
  const hit = await one(
    "SELECT id FROM custom_domains WHERE domain = $1 AND status IN ('verified','active')",
    [domain],
  );
  // Also accept the `www.` variant — we serve both in the Caddy snippet.
  if (!hit && domain.startsWith("www.")) {
    const apex = domain.slice(4);
    const hit2 = await one("SELECT id FROM custom_domains WHERE domain = $1 AND status IN ('verified','active')", [apex]);
    if (hit2) return res.status(200).send("ok");
  }
  return hit ? res.status(200).send("ok") : res.status(404).send("no");
});
