/**
 * Hourly sweeper that unpublishes free-tier sites past their 7-day TTL.
 *
 * For each expired row:
 *   1. `rm -rf /var/seosites/<slug>/` (removes the served files)
 *   2. DELETE FROM publishes  (frees the slug)
 *
 * Custom domains attached via FK CASCADE go with it. Caddy's dynamic.caddy
 * gets regenerated by the next domain add/remove (not by us) — until then,
 * any orphaned domain on an expired publish will serve a 404 from Caddy's
 * fall-through, which is fine.
 */

import path from "node:path";
import fs from "fs-extra";
import { query } from "./db";

const CHECK_INTERVAL_MS = 60 * 60 * 1000; // 1 hour
const SEOSITES_ROOT = process.env.SEOSITES_ROOT || "/var/seosites";

interface ExpiredRow { id: string; slug: string; project_id: string }

async function sweep(): Promise<void> {
  let rows: ExpiredRow[];
  try {
    rows = await query<ExpiredRow>(
      `SELECT id, slug, project_id FROM publishes
        WHERE expires_at IS NOT NULL AND expires_at < now()`,
    );
  } catch (err: any) {
    console.error("[publish-expirer] query failed:", err?.message || err);
    return;
  }
  if (rows.length === 0) return;

  for (const r of rows) {
    try {
      await fs.remove(path.join(SEOSITES_ROOT, r.slug));
      await query("DELETE FROM publishes WHERE id = $1", [r.id]);
      console.log(`[publish-expirer] expired ${r.slug}.seosites.app (project ${r.project_id})`);
    } catch (err: any) {
      console.error(`[publish-expirer] failed to expire ${r.slug}:`, err?.message || err);
    }
  }
}

export function startPublishExpirer(): void {
  console.log(`[publish-expirer] running, sweeps every ${CHECK_INTERVAL_MS / 60_000}min`);
  // Sweep once at boot so an orchestrator restart doesn't extend any TTLs.
  sweep();
  setInterval(sweep, CHECK_INTERVAL_MS);
}
